# Background and foreground colors
background = #000000
foreground = #C8A889

# Standard colors
palette = 0=#000000
palette = 1=#b68860
palette = 2=#d8bd76
palette = 3=#ffe894
palette = 4=#ab695e
palette = 5=#e09470
palette = 6=#e4db78
palette = 7=#C8A889

# Bright colors
palette = 8=#686163
palette = 9=#d49b68
palette = 10=#f6d373
palette = 11=#ffe97d
palette = 12=#ca796b
palette = 13=#ffa375
palette = 14=#fef374
palette = 15=#fcf4ea
