background            #000000
foreground            #C8A889

# black
color0  #000000
color8  #686163

# red
color1  #b68860
color9  #d49b68

# green
color2  #d8bd76
color10 #f6d373

# yellow
color3  #ffe894
color11 #ffe97d

# blue
color4  #ab695e
color12 #ca796b

# magenta
color5  #e09470
color13 #ffa375

#cyan
color6  #e4db78
color14 #fef374

#white
color7  #C8A889
color15 #fcf4ea


